apisix:
  node_listen:
    - port: 9080
  enable_ipv6: false
  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9090
deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    admin_listen:
      port: 9180
    allow_admin:
      - 0.0.0.0/0
    admin_key:
      - name: "admin"
        key: "881ab094e74b46cd8cd11dbf29032ce1"
        role: admin
  etcd:
    host:
      - http://etcd:2379
    prefix: /apisix
    timeout: 5